name: Push to Slack

on: push

jobs:
  my-job:
    name: Push to Slack
    runs-on: ubuntu-latest
    steps:
      - name: Post a message in a channel
        
        env:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
