- name: Post a message in a channel

on:
  workflow_call:
    inputs:
      workflow-event:
        required: true
        type: string
    secrets:
      slackWebhookUrl:
        required: true

jobs:
  notify:
    name: PR notification
    runs-on: [ubuntu-latest]
    steps:
      - name: Post message
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "title": ${{ toJson(fromJson(inputs.workflow-event).title) }},
              "author": ${{ toJson(fromJson(inputs.workflow-event).user.login) }},
              "link": ${{ toJson(fromJson(inputs.workflow-event).html_url) }}
            }
