name: Push to Slack

on: 
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'bump'
jobs:
  my-job:
    name: Push to Slack
    runs-on: ubuntu-latest
    steps:
      - name: Post a message in a channel
        
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: act10ns/slack@v2.1.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
